Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 43, in sys_call_Linux
    subprocess.run(dataList)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'recon-ng'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/recon.py", line 75, in __init__
    functions[inputs.index(data.split(" ")[0])](data)
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 117, in __init__
    self.GetData([ip, subnet, host])
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 129, in GetData
    print(funcs[inputs.index(data)]())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 91, in help
    if a in os.listdir(".data/.helpRecon"):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.data/.helpRecon'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/recon.py", line 75, in __init__
    functions[inputs.index(data.split(" ")[0])](data)
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 117, in __init__
    self.GetData([ip, subnet, host])
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 129, in GetData
    print(funcs[inputs.index(data)]())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/startNetworkRecon.py", line 92, in help
    with open(f".data/.helpRecon/{a}", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.data/.helpRecon/all'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 43, in sys_call_Linux
    subprocess.run(dataList)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'reon'
